steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=myproject
  - --key=key3
  
# Install
- name: 'gcr.io/cloud-builders/yarn'

# Build
- name: 'gcr.io/cloud-builders/yarn'
  args: ['generate']

# Deploy
- name: 'gcr.io/cloud-builders/yarn'
  args: ['deploy']